version: "3.9"

services:
  backend:
    build: .
    container_name: peerpilot-backend
    restart: always
    environment:
      SQLALCHEMY_DATABASE_URI: ${DATABASE_URL}
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
